## Config, just as the title says
## edited 2013.08.26

name: "Clara Tse"
description: "A portfolio of experience and past works for Clara Tse."
language: en-AU
markdown: rdiscount
paginate: 2
baseurl: http://claratse.com
keywords: "Clara Tse, Claira Tse, Claire Tse, Clare Tse, physdelia, sheetglass, anime, manga, otaku, artist, marketing, social media, web, designer, photography, kawaiikiri, onigirikiri, hanezawakirika, herbalinfusion, Sydney, Australia, Bachelor of Information Technology, BIT"

permalink: /:title/
timezone: Australia/Sydney
assets: https://dl.dropboxusercontent.com/u/158866275/personal

author:
  name: Clara Tse
  url: http://claratse.com
  twitter: hanezawakirika
  adn: kiri
  github: ctse